//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obracun_placa
{
    using System;
    using System.Collections.Generic;
    
    public partial class bonus
    {
        public int ID_bonus { get; set; }
        public Nullable<double> regres { get; set; }
        public Nullable<double> bozicnica { get; set; }
        public Nullable<double> uskrsnica { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<double> ukupno { get; set; }
    
        public virtual radnik radnik { get; set; }
    }
}
