//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obracun_placa
{
    using System;
    using System.Collections.Generic;
    
    public partial class doprinosNA
    {
        public int ID_doprinosNA { get; set; }
        public string naziv { get; set; }
        public Nullable<double> koeficijent { get; set; }
    
        public virtual placa placa { get; set; }
    }
}
