//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obracun_placa
{
    using System;
    using System.Collections.Generic;
    
    public partial class placa
    {
        public int ID_placa { get; set; }
        public Nullable<int> visina { get; set; }
        public string vrsta { get; set; }
        public Nullable<int> ukupno_bruto { get; set; }
        public Nullable<int> ukupno_neto { get; set; }
        public Nullable<int> ukupno_trosak { get; set; }
        public Nullable<int> dohodak { get; set; }
        public string obracun { get; set; }
    
        public virtual prirez prirez { get; set; }
        public virtual radnik radnik { get; set; }
    }
}
