//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obracun_placa
{
    using System;
    using System.Collections.Generic;
    
    public partial class radniSati
    {
        public int ID_radniSati { get; set; }
        public string vrsta_rada { get; set; }
        public Nullable<int> broj_sati { get; set; }
    
        public virtual radnik radnik { get; set; }
    }
}
