//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlaceEntities : DbContext
    {
        public PlaceEntities()
            : base("name=PlaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doprinosIZ> doprinosIZ { get; set; }
        public virtual DbSet<doprinosNA> doprinosNA { get; set; }
        public virtual DbSet<obracun_placa> obracun_placa { get; set; }
        public virtual DbSet<odbitakClan> odbitakClan { get; set; }
        public virtual DbSet<odbitakZaDjecu> odbitakZaDjecu { get; set; }
        public virtual DbSet<placa> placa { get; set; }
        public virtual DbSet<poslodavac> poslodavac { get; set; }
        public virtual DbSet<prirez> prirez { get; set; }
        public virtual DbSet<radnik> radnik { get; set; }
        public virtual DbSet<radniSati> radniSati { get; set; }
        public virtual DbSet<sati_blagdani> sati_blagdani { get; set; }
        public virtual DbSet<sati_bolovanje> sati_bolovanje { get; set; }
        public virtual DbSet<sati_godisnji> sati_godisnji { get; set; }
    }
}
