//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class obracun_placa
    {
        public int ID_obracun { get; set; }
        public string vrsta_obracuna { get; set; }
        public Nullable<int> godina { get; set; }
        public string mjesec { get; set; }
        public string dan { get; set; }
    
        public virtual placa placa { get; set; }
    }
}
