//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class placa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public placa()
        {
            this.doprinos_na_ukupno = new HashSet<doprinos_na_ukupno>();
            this.doprinos_iz_ukupno = new HashSet<doprinos_iz_ukupno>();
        }
    
        public int ID_placa { get; set; }
        public string visina_place { get; set; }
        public string vrsta_place { get; set; }
        public string prirez_ID { get; set; }
        public string obracun_ID { get; set; }
        public string stanje_ID { get; set; }
    
        public virtual radnik radnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doprinos_na_ukupno> doprinos_na_ukupno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doprinos_iz_ukupno> doprinos_iz_ukupno { get; set; }
        public virtual prirez prirez { get; set; }
        public virtual obracun_placa obracun_placa { get; set; }
        public virtual stanje stanje { get; set; }
    }
}
