//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class sati_godisnji
    {
        public int ID_godisnji { get; set; }
        public string pocetak_godisnji { get; set; }
        public string kraj_godisnji { get; set; }
        public Nullable<int> broj_sati { get; set; }
        public Nullable<int> radnik_ID { get; set; }
    
        public virtual radnik radnik { get; set; }
    }
}
