//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektni_zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class stanje
    {
        public int ID_stanje { get; set; }
        public Nullable<int> ukupno_bruto { get; set; }
        public Nullable<int> ukupno_neto { get; set; }
        public Nullable<int> ukupan_trosak { get; set; }
        public Nullable<int> dohodak { get; set; }
        public Nullable<int> ukupno_doprinosiIZ { get; set; }
        public Nullable<int> ukupno_doprinosiNA { get; set; }
    
        public virtual placa placa { get; set; }
    }
}
